# Generated by Django 4.2.7 on 2023-11-24 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('addressStreet', models.CharField(max_length=50)),
                ('addressLocality', models.CharField(max_length=50)),
                ('addressPostcode', models.CharField(max_length=6)),
                ('addressCity', models.CharField(max_length=50)),
                ('IC', models.CharField(max_length=10)),
            ],
        ),
    ]
