# Generated by Django 4.2.7 on 2023-11-29 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_event_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='client_id',
            new_name='client',
        ),
    ]
